name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93f7c2e5ed62ad891b15d6041c4ad73448f22e12c0440ecc90c143adf602c80d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
