name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e19824ff745a7e30cd17d0f6416b076f5e20c2d37cc97853197b57f7eafd9a25"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
