name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4985ac902b6e5532efdd881941ddeca41079a69b172a9435dc243e4d7c0ae87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
