name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b00ff0f6479ed795f2c0f28795e941a41201dbe302de8992cda2d4407f35b61c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
